// src/data/DentalItems.js

export const dentalItems = [
  "Toothbrush",
  "Dental Floss",
  "Mouth Mirror",
  "Dental Drill",
  "Scaler",
  "Forceps",
  "Prophy Paste",
  "Suction Tip",
  "Cotton Rolls",
  "Impression Tray",
  "Explorer",
  "Periodontal Probe",
  "Curette",
  "Amalgam Carrier",
  "Composite Gun",
  "Gloves",
  "Face Mask",
  "Dental Bib",
  "Syringe",
  "Anesthetic Cartridge",
  "Articulating Paper",
  "Cotton Pellets",
  "Dental Tray Stand",
  "Saliva Ejector",
  "High Speed Handpiece",
  "Low Speed Handpiece",
  "Dental Bur Kit",
  "Endodontic Files",
  "Temporary Filling Material",
  "Rubber Dam",
  "Rubber Dam Clamp",
  "Rubber Dam Punch",
  "Cavity Liner",
  "Glass Ionomer Cement",
  "Etching Gel",
  "Bonding Agent",
  "Composite Resin",
  "Amalgam Filling",
  "Dental Elevator",
  "Periodontal Ligament Probe",
  "Tongue Depressor",
  "Cheek Retractor",
  "Face Shield",
  "Dental Chair Light",
  "Disposable Cups",
  "Mouth Props",
  "Gauze Pads",
  "Sterilization Pouches",
  "Autoclave Indicators",
  "Patient Napkin",
  "Dental Tray Covers",
  "Endodontic Sealer",
  "Root Canal Filling Material",
  "Disposable Needles",
  "Surgical Blades",
  "Hemostats",
  "Dental Tweezers",
  "Burnisher",
  "Carver",
  "Spatula",
  "Mixing Well",
  "Impression Material",
  "Alginate Powder",
  "Dental Stone",
  "Plaster of Paris",
  "Vacuum Forming Sheets",
  "Bite Registration Material"
];
